### PR TITLE
Added leaderboard display API and tests

### LINKED ISSUE #19: View Leaderboard
One of the most important APIs for the project 

1. This will allow contributors to view the leaderboard and watch their competitors.
2.  A `[get] /leaderboard/` API that lists the contributors sorting them in the descending order of their points :v:

### PR DESCRIPTION
**Pull request by priyanshisharma**
Fixes #19 
This is a very well pointed out issue. 😂🎉
I have added the leader board API which returns all the fields of the `Leaderboard` model along with a field `rank` in descending order of points. Test for the same have been added in `tests_leaderboard_list.py`.

### CODE REVIEW

**Comment by anshsrtv** [comment]
U know what, I was working on the same issue and my branch was [view_leaderboard](https://github.com/anshsrtv/leaderboard-project/tree/view_leaderboard) :joy: :sob:

**Comment by priyanshisharma** [comment]
That does sound kinda sad 😅😓,.. I guess you will never forget to self assign issues now onwards 😅👀

**Comment by anshsrtv** [comment]
> That does sound kinda sad ,.. I guess you will never forget to self assign issues now onwards

Did you do that before your PR? :sweat_smile:  :angry:

**Comment by priyanshisharma** [comment]
I did it first 😂😂.. Don't worry I'll take a lesson to make sure I self assign from this too 🙈🙃

**Comment by priyanshisharma** [comment]
Hehe.. Thanks a ton!!! 🚀🎉😀🥳 
Yeah it is most welcome 😂

**Pull request merged**
